### PR TITLE
Improved

### PR DESCRIPTION
**Pull request by ghost**
a ton of improvements

### CODE REVIEW

**Comment by RealJakeTheDog** [comment]
Verifying that there are no obvious issues with this code. The reason I had the scan and start files separate are so that you could run multiple scans at once. If this isn't too much slower, I will just full commit this to the main branch.

**Comment by RealJakeTheDog** [comment]
This code currently has an issue where it is only scanning for anydesk (The first RAT in the list). Working on a fix now.

**Comment by ghost** [comment]
i have fixed the issue with the second latest commit

**Comment by RealJakeTheDog** [comment]
Same issue is still occurring.
For Reference -> `
"Please input the folder or drive you want to scan (leave blank for full system scan):"

"Running scan, this may take some time..."
"Scanning AnyDesk"
"AnyDesk.lnk"
"Found C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\AnyDesk.lnk"
ERROR: The process "AnyDesk*" not found.
The system cannot find the path specified.
The system cannot find the file specified.
The system cannot find the path specified.
"AnyDesk.lnk"
"Found C:\Users\All Users\Microsoft\Windows\Start Menu\Programs\Startup\AnyDesk.lnk"
ERROR: The process "AnyDesk*" not found.
The system cannot find the path specified.
The system cannot find the file specified.
The system cannot find the path specified.
The system cannot find the path specified.
"No Remote Access Tools were found. Exiting now"

Waiting for  6 seconds, press a key to continue ...`

**Comment by RealJakeTheDog** [comment]
I have fixed the issue with it only scanning for one thing at a time. Merging the current version with main branch and adding improvement.

**Pull request merged**
